apiVersion: v1
kind: Service
metadata:
  name: code-executor-service
  namespace: nfpiet
  labels:
    app: code-executor

spec:
  selector:
    app: executor
  ports:
  - port: 3030
    targetPort: 3000